name: Build CUDA LLVM

on:
  workflow_dispatch:
  push:
    branches:
      - main
  # pull_request:
  #   paths:
  #     - ".github/workflows/build.yml"
  #     - "docker/**"
  #     - "build.sh"

concurrency:
  group: llvm-cuda-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_HUB_NAMESPACE: jackaltsai

jobs:
  build_img:
    name: Build ${{ matrix.tag-suffix }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        tag-suffix: ["llvm14_elixir"]
        include:
          - tag-suffix: "llvm14_elixir"
            BASE_IMAGE: "elixir:1.9.4"
            LLVM_VERSION: "14"
    env:
      DOCKER_REPO: "${{ matrix.tag-suffix }}"
      BASE_IMAGE: "${{ matrix.BASE_IMAGE }}"
      LLVM_VERSION: "${{ matrix.LLVM_VERSION }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
          cache-to: type=inline
          context: ./llvm-ex
          build-args: |
            BASE_IMAGE
            LLVM_VERSION
